### PR TITLE
Сomprehensive update init system.

### PR DESCRIPTION
**Pull request by Realex-fire**
1)Fixed STweaks install.
2)Fixed BLN.
3)Rename Lollipop-CM-AOKP-12.1 to Lollipop-CM-AOSP-12.1 because it is not supported AOKP roms.
4)Correction of various logical errors in post-init.sh and install.sh
5)Other cosmetic changes in init scripts.
6)rm "scheduler~"

PS: https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/commit/d9432c3d87e26c09d6bad03ecdc22015ea4a9638 - it is no longer necessary.

### CODE REVIEW

**Comment by gsstudios** [comment]
You're a legend. Cheers mate. Will test soon :) Thanks!

**Comment by gsstudios** [comment]
Wait, does it mean that other ROMs should work now? Never mind. Was just rename so it makes more sense

**Comment by gsstudios** [comment]
Seem to have corrupted my OS. Now it won't boot. Will need to restore from scratch. 

gsstudios

**Comment by Realex-fire** [comment]
I'll deal with it today.

**Comment by Realex-fire** [comment]
It's just a typo in
$BB cp -a /res/misc/Lollipop-CM_AOSP-12.1/\* /;
Fixed:
$BB cp -a /res/misc/Lollipop-CM-AOSP-12.1/\* /;

**Comment by gsstudios** [comment]
Got it, will test soon again :)

**Comment by gsstudios** [comment]
Works well. Can confirm stweaks is installed on kernel install and BLN is working. Thanks !!

**Comment by arny24x7** [comment]
What changes u made to fix BLN without lights.c support ???

**Pull request merged**
